### ISSUE TITLE
Allow download of available data

### ISSUE THREAD

**Issue by jenniferboedker** [qbicsoftware/sample-tracking-status-overview#47]
As a DA, I want to access a project and download all available sequencing raw data so that I can start analyzing them.

The user can download a download manifest, that contains the sample codes of all samples where raw data is available. Along the manifest file the user is guided to a manual in order to understand how he can retrieve his data through `postman`.

**Comment by jenniferboedker** [comment]
also see #13

**Comment by jenniferboedker** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User Story: As a DA, I want to access a project and download all available sequencing raw data so that I can start analysing them](https://trello.com/c/sDMsrLxl/912-user-story-as-a-da-i-want-to-access-a-project-and-download-all-available-sequencing-raw-data-so-that-i-can-start-analysing-them)

**Comment by KochTobi** [comment]
[ST-2]

**Comment by jenniferboedker** [comment]
The current draft for how the download is implemented in the view looks like this. A single button allows for the download of all samples for a selected project

![Screenshot 2021-08-23 at 15 56 23](https://user-images.githubusercontent.com/20778777/130459866-b006fa9d-434f-414c-9c87-e9cd9e3c86ce.png)
